homeassistant:

  latitude: 59
  longitude: 26
  temperature_unit: C
  time_zone: Europe/Tallinn

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend
#conversation:

# Show links to resources in log and frontend
#introduction:

hello_world:
group:
  lights:
    - switch.living_room_led
  sensors:
    - sensor.pir_living_room
    - sensor.time
  Humidity:
    - sensor.humidity_sensor
  Temperature:
    - sensor.temperature_sensor

binary_sensor 1:
  platform: rpi_gpio
  name: PIR_LIVING_ROOM
  ports:
    4: pir_living_room
  pull_mode: "UP"
  bouncetime: 50
  invert_logic: false

sensor 1:
  platform: command_sensor_custom
  scan_interval: 1
  name: "time"
  command: "date"

sensor 2>
  platform: command_sensor_custom
  scan_interval: 1
  name: "humidity_sensor"
  command: "/root/.homeassistant/humidity_sensor.py"

sensor 3:
  platform: command_sensor_custom
  scan_interval: 1
  name: "temperature_sensor"
  command: "/root/.homeassistant/temperature_sensor.py"
  
switch 1:
  platform: command_switch
  switches:
    living room led:
      oncmd: "/root/.homeassistant/light_on.py"
      offcmd: "/root/.homeassistant/light_off.py"

input_select:
  fan_temperature:
    name: Fan Temperature
    options:
     - 10 C
     - 20 C
     - 30 C
  light_condition:
    options:
      - Valge
      - Hamar
      - Pime
  light_curtain_condition:
    options:
      - Lights off when curtains open
      - Lights on when curtains open
      - Home Alone
  living_room_preset:
    options:
      - Visitors
      - Visitors with kids
      - Home Alone

automation:
- alias: "Turn on LED"
  trigger:
    platform: state
    entity_id: binary_sensor.pir_living_room
    # Optional
    from: 'off'
    to: 'on'
  action:
    entity_id: switch.living_room_led
    service: switch.turn_on

- alias: "Turn off LED"
  trigger:
    platform: state
    entity_id: binary_sensor.pir_living_room
    # Optional
    from: 'on'
    to: 'off'
  action:
    entity_id: switch.living_room_led
    service: switch.turn_off


