TEMP_SENSOR = 4               #entity_id temp_sensor
HUMIDITY_SENSOR = 4           #entity_id humidity_sensor
PIR_CORNER = 10               #entity_id pir_corner
LED_CORNER = 9				  #entity_id led_corner
LED_BEDROOM = 11			  #entity_id led_bedroom
PELTIER = 5					  #entity_id peltier
LIGHT_SENSOR = 6              #entity_id light_sensor
STEPPER_WINDOW_ENABLE = 13	  #entity_id stepper_window
STEPPER_WINDOW_STEP = 19
STEPPER_WINDOW_DIR = 26
PIR_LOBBY = 23				  #entity_id pir_lobby
PIR_KITCHEN = 24              #entity_id pir_kitchen
LED_OUTSIDE = 25                #entity_id led_lobby
LED_KITCHEN = 8				  #entity_id led_kitchen
FAN = 12                      #entity_id fan
STEPPER_DOOR_ENABLE = 16      #entity_id stepper_door
STEPPER_DOOR_STEP = 20
STEPPER_DOOR_DIR = 21
